### ISSUE TITLE
INDEX Header Size appears misrepresented 

### ISSUE THREAD

**Issue by ringo380** [jeremycole/innodb_diagrams#1]
Heya,

Just wanted to point out that the total of the values shown in the INDEX HEADER diagram is 32 bytes, while the size that appears to be represented in the labels would indicate that the total is 36 bytes (74-38). It looks like this is due to a "mystery" 4-byte padding that exists prior to the Index ID value - either that or the index ID is stored across 8 bytes instead of 4.

Thanks  again for all your work on this stuff!

**Comment by jeremycole** [comment]
Howdy, thanks for the report! You're definitely correct, the "Index ID" field is actually 8 bytes, not 4. You can actually see the read of the uint64 in [lib/innodb/page/index.rb](https://github.com/jeremycole/innodb_ruby/blob/master/lib/innodb/page/index.rb#L223).

I will fix the diagram.

**Comment by jeremycole** [comment]
Fixed in 6e952a7!
